### PR TITLE
Update Emanuele Cisbani IETF document to latest Metanorma markup 

### PR DESCRIPTION
**Pull request by manuelfuenmayor**
As requested in https://github.com/metanorma/metanorma/issues/295#issuecomment-1766293683

### CODE REVIEW

**Comment by cisba** [comment]
The good news: now I can compile without any error just running 
```
git fetch origin pull/1/head && git checkout FETCH_HEAD
snap/bin/metanorma -t ietf -x html,txt draft-intesigroup-dlts.adoc
```

The bad news: I found some **content** issues in metadata and bibliography
``
diff -W 152 -y draft-intesigroup-dlts-07.txt draft-intesigroup-dlts.txt | less -S
``

I attach also screenshots to easily identify them, hoping you can help me fix them.
[issues.zip](https://github.com/cisba/i-d_dlts/files/13040130/issues.zip)

**Comment by manuelfuenmayor** [comment]
@cisba,
The document metadata is completely fixed in https://github.com/cisba/i-d_dlts/pull/1/commits/34910c2bf58786f8611472c87926035f9f00bcc2
Some attributes were deprecated. I refer you to this website for the latest attributes on IETF: https://www.metanorma.org/author/ietf/ref/document-attributes/

In regard to the references, there was a typo in several instances. They are fixed now in https://github.com/cisba/i-d_dlts/pull/1/commits/45c27830d875e04eab0fd6102dc2ea8568dcedc2.
Other reference issues are due Metanorma bugs, I'm afraid. I've reported them to the corresponding departments.

In general, however, the generated output is closer to the expected result.

**Comment by cisba** [comment]
> @cisba, The document metadata is completely fixed in [34910c2](https://github.com/cisba/i-d_dlts/commit/34910c2bf58786f8611472c87926035f9f00bcc2) Some attributes were deprecated. I refer you to this website for the latest attributes on IETF: https://www.metanorma.org/author/ietf/ref/document-attributes/

Fantastic, your help is a gift, thanks a lot!
 
> In regard to the references, there was a typo in several instances. They are fixed now in [45c2783](https://github.com/cisba/i-d_dlts/commit/45c27830d875e04eab0fd6102dc2ea8568dcedc2). Other reference issues are due Metanorma bugs, I'm afraid. I've reported them to the corresponding departments.
> 
> In general, however, the generated output is closer to the expected result.

I agree, the document now is quite good.

I noted one issue not related to references but in the conventions section:
```
[[conventions]]
== Terms and Definitions

The key words "*MUST*", "*MUST NOT*", "*REQUIRED*", "*SHALL*",
"*SHALL NOT*", "*SHOULD*", "*SHOULD NOT*", "*RECOMMENDED*",
"*NOT RECOMMENDED*", "*MAY*", and "*OPTIONAL*" in this
document are to be interpreted as described in BCP 14
```
is rendered as below:
```
3.  Terms and definitions

   The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
   "SHOULD", "SHOULD NOT", "RECOMMENDED", "*NOT RECOMMENDED*", "MAY",
   and "OPTIONAL" in this document are to be interpreted as described in BCP 14
```
As you can see, asterisks are mantained just for "*NOT RECOMMENDED*" term.
Is also this an issue due to a Metanorma bug?

Finally, about Metanorma bugs reported, I see just a link referring to one of them, are there others public links you can share here?

Let me know if I can contribute in some way. I hope my document will be useful to Metanorma improvement.

Kind Regards
Emanuele

**Comment by manuelfuenmayor** [comment]
> I noted one issue not related to references but in the conventions section:

Yes, this issue is already fixed. You should note the changes on next release (in about a week).

> Finally, about Metanorma bugs reported, I see just a link referring to one of them, are there others public links you can share here?

Hm, that's odd. In my case, I can see all the links without having to sign into GitHub. These are the links:

* https://github.com/metanorma/metanorma-ietf/issues/189
* https://github.com/relaton/relaton-nist/issues/107
* https://github.com/relaton/relaton-ietf/issues/119
* https://github.com/relaton/relaton-iso/issues/155

Please let me know which link(s) you cannot see.
(Ah, I see what happened. The other links are shown above the link you saw.)

**Comment by cisba** [comment]
> Please let me know which link(s) you cannot see. (Ah, I see what happened. The other links are shown above the link you saw.)

Yeah, I missed some link, now I can see all the 4. Thanks!

Anyway it seems to me that there are still two issues to track.

1. In CrosbyWallach reference, series:: info are lost in rendering:
CrosbyWallach

2. In HaberStornetta reference, structured_identifier.year:: 1991 is lost in rendering:
HaberStornetta

**Comment by manuelfuenmayor** [comment]
> In CrosbyWallach reference, series:: info are lost in rendering:

Yes, I forgot to report that (possible) bug. It is now in https://github.com/relaton/relaton-render/issues/48

> In HaberStornetta reference, structured_identifier.year:: 1991 is lost in rendering:

This is a markup error. Fixed in https://github.com/cisba/i-d_dlts/pull/1/commits/d889bfd300b50a7eac5c4dc5e7c1a971d98889db.

Thanks!

**Comment by cisba** [comment]
Just to recap the current open issues:
* https://github.com/metanorma/metanorma-ietf/issues/190
* https://github.com/metanorma/metanorma-ietf/issues/191
* https://github.com/relaton/relaton-ietf/issues/119
* https://github.com/relaton/relaton-render/issues/48

@manuelfuenmayor One question: how can I sort reference alphabetically inside the Informative Reference section?
For example I would like to put ISO.IEC.18014-4 and RFC6962 not at the beginning of the list,as you did, but in the right position according to the alphabetical order, to be easily found by the reader. When I move it in the source, the compilation fails. Maybe there is some syntactical rule or trick that I don't know... can you help me?

**Comment by manuelfuenmayor** [comment]
I'm not sure if we have alphabetic sorting feature available for informative references. In fact, the order of the references seems to be positional in correspondence with the markup. Maybe @opoudjis can help us on this one?

**Comment by opoudjis** [comment]
There is no such trick currently.

I will review the RFC XML v3 spec and see what discussion there has been, if any, about sorting references, and what has currently been implemented as the sort order.

https://github.com/metanorma/metanorma-ietf/issues/192

But I have had a backlog of 100 tickets for the past 3 years, and one of the major reasons for that is making things more flexible for users. And you will have noticed how unresponsive I have been for the past three weeks: I have been knee-deep in ISO 10303, which has an end-of-year deadline, and is extremely difficult to keep straight.

So the answer to that question may be "no", depending on how it is currently implemented, and what the existing practice is.

One thing that may short circuit this entire discussion: try 

`:sort-refs:`

in the document header attributes. That passes on the sort-refs directive to xml2rfc, and if that directive is working, it may sort the references the way IETF wants to see them sorted.

@cisba if you have any pointers to forum discussions or guidelines about sorting references in RFC, that would help.

**Comment by manuelfuenmayor** [comment]
> One thing that may short circuit this entire discussion: try
> :sort-refs:

It produces compilation failure.

**Comment by cisba** [comment]
> @cisba if you have any pointers to forum discussions or guidelines about sorting references in RFC, that would help.

I did not find any discussion or guidelines except an old issue in xml2rfc:

* https://github.com/ietf-tools/xml2rfc/issues/210

And it seems not solved.

Anyway an automatic sorting feature is not necessary, IMHO.

I'll be happy being able to manually sort references in the src file.

Unfortunately I did not find a way to do it without breaking the compilation. 

When I put an ISO or an RFC reference after a [%bibitem] section, the compilation fails!

**Comment by opoudjis** [comment]
Yeah, `[%bibitem]` is not intended to be interleaved with Asciidoctor bibliographic lists—it's lists vs clauses, which are at different hierarchical levels. I would recommend using the span notation instead, as both easier to read and better integrated into Asciidoctor bibliographies: https://www.metanorma.org/author/topics/document-format/bibliography/#annotated-spans

**Comment by opoudjis** [comment]
Working on this PR is presenting a large number of challenges for me, and I am unable to tell whether @manuelfuenmayor is working on supported or unsupported versions of Metanorma and Ruby.

So, to both @cisba and @manuelfuenmayor: 

* @manuelfuenmayor if you have not already, delete the file ".ruby-version", with EXTREME PREJUDICE. We do not support Ruby 2.6.x: we restrict our support to currently supported versions of Ruby (which is why our release testing taks a full day, testing all of them).
* Ensure that the Gemfile is not locked in to a **five-year-old** version of Metanorma (metanorma-ietf 1.0.1, dating from 2019!!) We only support reasonably recent versions of our code; this version, which predates massive refactoring of the IETF code, is not reasonably recent.
* We have stopped supporting RFC XML v2 with our major refactor of metanorma-ietf, which brought it in line with the other SDOs we support. We have severely limited resources (and I know that well, being the  sole maintainer of Metanorma outside its PDF output), and we cannot justify maintaining both v2 and v3.

I cannot yet work out whether the tickets have been reported against 1.0.1 or the current 3.2.2, but this is part of the necessary transition if we are to support you, @cisba . And deleting .ruby-version and updating Gemfile.lock do need to be reflected in the PR to reflect that.

**Comment by opoudjis** [comment]
I'll add that right now, I cannot get the RFC XML v3 output in this directory to compile through rfc2xml, which suggests to me that @cisba should not be getting meaningful output yet. @manuelfuenmayor Please double check that it is compiling with current Ruby and Metanorma, @cisba could be getting false positives. Then again, the document header is requesting `rfcxml2`, which tells me that both of you have been dealing with the four-year-old version of code.

In particular, the references appear under v3 to be quite mangled. Are you getting these errors?

````
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(39): Error: Did not expect element t there, at /rfc/front/abstract/t/t
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(441): Error: Did not expect element t there, at /rfc/back/references[1]/t[1]
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(441): Error: Element references has extra content: t, at /rfc/back/references[1]/t[1]
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(571): Error: Did not expect element t there, at /rfc/back/references[2]/t[1]
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(571): Error: Element references has extra content: t, at /rfc/back/references[2]/t[1]
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "ETSI.EN.319.422", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC5652", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC5652", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC5652", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC5652", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC8174", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "ETSI.TS.102.778-4", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC6962", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "Merkle", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "Nakamoto", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "OTS", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "IMES", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC4210", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC4210", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC2119", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "OpenTimestamps", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3161", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3161", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3161", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3161", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3161", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3161", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3161", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3161", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3161", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC6838", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "eIDAS", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "ANSI.X9.95", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "ETSI.TS.101.861", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC3628", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "Hyperledger", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "NISTIR_8202", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "ISO.IEC.18014-4", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "UK-GCSA", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "HaberStornetta", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC5280", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC5280", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "RFC5280", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "CrosbyWallach", at None
/Users/nickn/Documents/Arbeit/upwork/ribose/i-d_dlts/draft-intesigroup-dlts.rfc.xml(0): Error: IDREF attribute target references an unknown ID "CrosbyWallach", at None
````

**Comment by cisba** [comment]
> I cannot yet work out whether the tickets have been reported against 1.0.1 or the current 3.2.2, but this is part of the necessary transition if we are to support you, @cisba . And deleting .ruby-version and updating Gemfile.lock do need to be reflected in the PR to reflect that.

All tickets have been reported by me using latest snap stable version.

Gemfile.lock and .ruby-version was necessary using the old Metanorma release.

Are they not ignored now by the current Metanorma snap package?
Please, can you delete all stuff not needed by the current Metanorma snap release?

**Comment by manuelfuenmayor** [comment]
@cisba, could you please share (upload) your output of this file: "draft-intesigroup-dlts.rfc.xml"?

**Comment by ronaldtse** [comment]
@cisba I've cleaned up the repository so it now fully works with the latest Metanorma versions and also RFC XML v3. Both `.ruby-version` and `Gemfile.lock` have been removed.

I've also added the GitHub Actions workflow so we can see the status of build.

The `:sort-refs:` attribute isn't work, I've filed the bug here:
* https://github.com/metanorma/metanorma-ietf/issues/194

Sorry that was really more noise than I expected from our team 🤣

**Comment by cisba** [comment]
> @cisba, could you please share (upload) your output of this file: "draft-intesigroup-dlts.rfc.xml"?

[draft-intesigroup-dlts.rfc.zip](https://github.com/cisba/i-d_dlts/files/13229191/draft-intesigroup-dlts.rfc.zip)

**Comment by cisba** [comment]
> @cisba I've cleaned up the repository so it now fully works with the latest Metanorma versions and also RFC XML v3. Both `.ruby-version` and `Gemfile.lock` have been removed.
> 
> I've also added the GitHub Actions workflow so we can see the status of build.
> 
> The `:sort-refs:` attribute isn't work, I've filed the bug here:
> 
>     * [`:sort-refs:` document attribute not working with xml2rfc metanorma/metanorma-ietf#194](https://github.com/metanorma/metanorma-ietf/issues/194)
>

Thank you very much!
 
> 
> Sorry that was really more noise than I expected from our team 🤣

No problem. Solved.

BTW, I think there is some more garbage to clean, but I'm not sure about the origin of them.

1. The files below was necessary in the old Metanorma release, now snapd package should not need them anymore. Is it correct?

- Gemfile
- Makefile
- requirements.txt

2. The files below are old outputs that can be removed from commits. Is it correct?
draft-intesigroup-dlts.nits
draft-intesigroup-dlts.xml

3. The files below I have no idea whre they came from. Can you give me a hint?
rfc2629.dtd
rfc2629-other.ent
rfc2629-xhtml.ent
rfc2629.xslt

**Comment by ronaldtse** [comment]
Question 1: I believe you can remove all of those files.

Question 2: Yes, correct. The easy way is to keep them in GitHub Releases.

Question 3: These files are used by the IETF tool `xml2rfc` which is the required publication last-stage for Internet-Drafts. Technically, you can also remove them without issues.

**Comment by manuelfuenmayor** [comment]
@cisba I've confirmed that the `:sort-refs:` attribute works properly now; the references are sorted in alphabetical order.
Is there something else that you need from us?

**Comment by cisba** [comment]
> @cisba I've confirmed that the `:sort-refs:` attribute works properly now; the references are sorted in alphabetical order. Is there something else that you need from us?

Now everything works perfectly. Great job. Thank you so much!

**Pull request merged**
